### ISSUE TITLE
not enough cta.

### ISSUE THREAD

**Issue by he3als** [kittehsq/kittehsq.github.io#1]
\>:((((

**Comment by he3als** [comment]
this was a shitpost, i apologise

**Comment by kittehsq** [comment]
this issue still persists

**Comment by kittehsq** [comment]
![breaking benches](https://user-images.githubusercontent.com/97140641/171614964-40d22fa7-7d20-4b8d-8133-3d096fdf300b.jpg)
![breaking benches](https://user-images.githubusercontent.com/97140641/171614975-0dd848c6-0641-4fd7-87c4-1a2293505fe7.png)
this is why there needs to be more cet images. (this is users when no cat image(

**Comment by he3als** [comment]
cet :(

**Comment by kittehsq** [comment]
lacking of cet

**Comment by he3als** [comment]
cet?

**Comment by kittehsq** [comment]
solution: javascript image parser
problem: javascript image parser

**Comment by he3als** [comment]
javasscript
